language: java
jdk:
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

addons:
  sonarcloud:
    organization: "manolodd"
    token:
      secure: "DeuKtKZBDMZ/f3CuQBmetWnIyHQCCWvcmQ4iIroqLA0JxI49vQamwtKWCKSR6rpwqr0FNMC+v9wIHu9Rg+w4Eg/7djIQ4zzAWq0+XL6C/oBZ0KSeUC9uLFJAIHCYhfdDzoeoVBWnkJdb3V3Ni5SotaV2LV1GxmytE1mZDF/mj4GNDCqGmbLDkq4Lqh7twcXXIDSqD58fCTjaaFUQRL43otpE1Vw5eDpfgwsJnP05hEzPJGdVCDQiLfTA9/oo3yy0AbtlCjKtbAT8tirQiIDz6aLt2dCIhWxpqEC/WB71EuHdxep/L+CzOBARh8wQpNsPr3OV6CnkYe6GuMlZ+CBxpsrRrhZESnMLdOa97qgQI3C1317351UDCQVQJRg8n8uB+HfzOADnDrTJAihzcxXVAhLzpvqMjUecy8kxuZWPdqAtn9IHNO2RM//qz6Qen+kPyzknJSMf1SZXHRw+5OvyUjV7JtMLWdG4le+vxJLX9BnfXji3UTa/ZDnQab9KX+6z/r8SEY43jCdnJVi4HdCHFt6iYttBhCwvRTZyh6X2+aOvTPEdBg1Gp8iFWAG9WDGcbCHP6v4DK+ZFKcwH/fr2AacIsmRFExmq05GWYt8yX3OAHzhRiUtBIo3tUuB0J5N4uat3Obf5XEccjUH2Z/RZv+wDZNkBtlvZFvZfl6cIRgM="


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=manolodd_openlrae
