language: java
jdk:
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

addons:
  sonarcloud:
    organization: "manolodd"
    token:
      secure: "UR8r7GoX468qwa8THbwpv/NaTPlWEf+eRC/IZ3V1mGSxHhjKttU68NojhRPopRDJ4q1mh3fB4VfS2f2pBxXJyIvl8+aOYd4f869ZXyYD77KYpExeO3lj00UGXk5chVJ1Cy8gpYAOgeaCdAacJ0u3pZpr0GvpWCqm7/NeardcOqxq4Rm3a2I+lz3+3HWbQdGcdA4NL7JWSPWR+nLoWqatYLG/mSKbTqC2R7neq7ECMh/qf0qPfyH9EPKzDWi8uBNo5wWdB7TV2j+YO+9FkZeFUZ+/IxqGa4cESO0ir/KKfA9UGYAR9gxI50nX4ns0M2jbIyZkU5u/hBKht8a0d6aB5M/uptOlWxEENi40kALwtcn94knbPlkE8eneKlJkRpklo6C3cGcxpCQRzEG6l16ANHigbw4kB9lObxO0q4IhbiyoGhyzMt9vWF22ahdSOQXktJtiaOD0g3ihi7LEiIoNSIVG87MgXftfJExPU5rBZFAIwc5MWd59SNpQiSjN9XSGNermgZcWGWoygKsU8wDUJnF6ZgWue4rVl9OA3nm6hrgbaXgxH8xAG8/yuw9WRadfDdGZz5rrySad85QVQllGMeMDydLvu9zyQgrFoCCnMxS5K6G7fD/IEQ2GOk/pSUyqly/Gs0/twtPjgYs7+Jo2CJYCpJCKgRyTLx8xGUZZJKE="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=manolodd_openlrae
